extends: default
ignore: |
    .git
    .idea
    /bin
    /src
    /tests
    /var
    /vendor
rules:
    document-start: disable
    line-length: disable
    braces:
        min-spaces-inside: 0
        max-spaces-inside: 1
    brackets:
        min-spaces-inside: 0
        max-spaces-inside: 1
    comments:
        require-starting-space: false
        min-spaces-from-content: 1
    indentation:
        spaces: 4
    comments-indentation: disable
