x-healthcheck: &x-healthcheck
    start_period: 15s
    start_interval: 3s

services:
    nats:
        image: 'nats:2.10.22-alpine'
        command:
            - '--jetstream'
        healthcheck:
            <<: *x-healthcheck
            test: 'echo -e PING | nc localhost 4222 | grep PONG'
    php:
        image: 'etriasnl/dev-php-fpm:8.1.31-43'
        user: '${HOST_UID:-0}:${HOST_GID:-0}'
        tty: true
        depends_on:
            nats:
                condition: service_healthy
        volumes:
            - '.:/app'
        environment:
            - CI
            - GITHUB_ACTIONS
            - RUNNER_DEBUG
            - TERM=xterm-256color
