version: '3'
services:
    nats:
        image: 'nats:2.10.11'
        command:
            - '--jetstream'
    php:
        image: 'etriasnl/dev-php-fpm:8.1.27-12'
        depends_on:
            - nats
        volumes:
            - '.:/app'
        environment:
            - CI
            - GITHUB_ACTIONS
            - RUNNER_DEBUG
