services:
    nats:
        image: 'nats:2.10.14'
        command:
            - '--jetstream'
    php:
        image: 'etriasnl/dev-php-fpm:8.1.28-22'
        depends_on:
            - nats
        volumes:
            - '.:/app'
        tty: true
        environment:
            - CI
            - GITHUB_ACTIONS
            - RUNNER_DEBUG
            - TERM=xterm-256color
