version: '3'
services:
    php:
        image: etriasnl/dev-php-fpm:8.1.24-90
        volumes:
            - '.:/app'
        environment:
            - CI
            - GITHUB_ACTIONS
            - RUNNER_DEBUG
