version: '3'
services:
    nats:
        image: nats:2.10.7
        command:
            - '--jetstream'
            - '--debug'
    php:
        image: etriasnl/dev-php-fpm:8.1.27-1
        depends_on:
            - nats
        volumes:
            - '.:/app'
        working_dir: /app
        environment:
            - CI
            - GITHUB_ACTIONS
            - RUNNER_DEBUG
