name: GitHub Delete Branch Cache

'on':
    pull_request:
        types: [ closed ]

jobs:
    delete:
        runs-on: ubuntu-latest
        steps:
            -
                uses: snnaplab/delete-branch-cache-action@v1.0.0
                with:
                    # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
                    ref: refs/pull/${{ github.event.number }}/merge
